name: xchg
version: 0.1.0-dev
description: XCHG Dart library.
repository: https://github.com/ipoluianov/dart-xchg

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  pointycastle: ^3.6.2
  crypto: ^3.0.2
  base32: ^2.1.3
  http: ^0.13.5
  archive: ^3.3.5
